### ISSUE TITLE
getting old code for the SVG when saving the avatar 

### ISSUE THREAD

**Issue by monikkacha** [psk907/fluttermoji#21]
Hello you have made awesome library and thanks for that .

we are using FlutterMoji functions to get SVG code and then converting it into .svg file 
`String encodeMySVGtoString = await FluttermojiFunctions().encodeMySVGtoString();`
`String decodeFluttermojifromString = await FluttermojiFunctions().decodeFluttermojifromString(encodeMySVGtoString);`

problem is that here `decodeFluttermojifromString` gives the code for previous avatar , not the one i have customize right now .

calling , FlutterMoji functions from onTap callback of `FluttermojiSaveWidget` . call back supposed to be trigger after after saving the svg changes in SharedPreference according to document . 
`Additonal callbacks to be triggered on tapping the widget after the save operation is executed.`

but looking at `flutterMojiSaveWidget.dart` found that `onTap` callback being called without waiting for ` fluttermojiController.setFluttermoji();` , which can be done by await and async .

can you please check at issue

**Comment by monikkacha** [comment]
@psk907 made PR which solves above issue : https://github.com/psk907/fluttermoji/pull/22

pls check and merge .

**Comment by Spiderbezno** [comment]
this pull is not available in pub.dev ???

**Comment by psk907** [comment]
PR #22  has been merged and new version is live on pub.dev
