### ISSUE TITLE
How to get the raw string given to SvgPicture

### ISSUE THREAD

**Issue by dri94** [psk907/fluttermoji#32]
I want to obtain the finalized SVG to save to my server. The SVG that can be used within the Fluttermoji library. I believe this is the same raw string that must be given to SvgPicture.string() for it to display. How do I obtain this?

**Comment by psk907** [comment]
Please look into the methods exposed by the FluttermojiFunctions class.
[API Documentation for the above](https://pub.dev/documentation/fluttermoji/latest/fluttermojiFunctions/FluttermojiFunctions-class.html#instance-methods)

**Comment by dri94** [comment]
For anyone wondering. I achieved it like this
```
            FluttermojiController? controller = avatar.buildGetX().init;
            Map<String?, int>? options =
                await controller?.getFluttermojiOptions();
            String? decoded = FluttermojiFunctions()
                .decodeFluttermojifromString(jsonEncode(options));
       ```
