### ISSUE TITLE
The emoji saves when I go back

### ISSUE THREAD

**Issue by akaAntox** [psk907/fluttermoji#4]
If I make a change to the emoji, even if I just go back without pressing the save icon, i see the changes.

**Comment by psk907** [comment]
Hi @akaAntox , yeah I noticed that the fluttermoji is temporarily saved despite going back and reverts only on app-relaunch.

I will work on a potential fix for this.
If you have gone through the source code and have any ideas, drop em' below.

**Comment by akaAntox** [comment]
I suggest you to use two different widgets for showing the avatar, one inside the edit avatar page and one to show it anywhere else

**Comment by psk907** [comment]
@akaAntox I have made necessary changes and updated the package to fix this issue. Update your dependency to 
```yaml
 fluttermoji: ^0.2.1
```
and check it out !
Alternatively you can try the [web demo](https://psk907.github.io/fluttermoji).

Let me know if this helped :)

**Comment by akaAntox** [comment]
Yes, it worked out well, amazing job!
