### ISSUE TITLE
telegram link not working

### ISSUE THREAD

**Issue by aakashpothepalli** [psk907/fluttermoji#8]
Telegram link is not working on my jio network

possible fix  - change t.me to telegram.me
![image](https://user-images.githubusercontent.com/19583729/124973367-108f6700-e049-11eb-8953-ae9be62aa99b.png)

**Comment by psk907** [comment]
The link seems to be working on my Jio network. Moreover Telegram encourages using `t.me` format, so we shall stick to the same.
Thank you.
