### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by skobak** [psk907/fluttermoji#9]
Hi, thank you for your work!

I would like to add the following customizations things:

1. Callback on 'save'
2. Set a custom save button out of the module, in other words, ability to use Controller method: setFluttermoji from outside
3. Ability to set custom fonts for text components inside the widget
4. Ability to programmable pre set image

Thanks in advance,
Best, Alex

**Comment by psk907** [comment]
Hey @skobak , yes those would be some really useful features and I will surely work on them.

In the meantime if you're interested in creating a PR for one them, please go ahead . 😊

Thank you.

**Comment by psk907** [comment]
These features have been implemented in v1.0.0 , do check them out !
